# Server settings  

server:  
  port: 8090  
#  address: 127.0.0.1
  session-timeout: 30  
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8  
  
spring:  
 # HTTP ENCODING  
  http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true 
        
  datasource:  
    url : jdbc:oracle:thin:@jian:1521:orcl
    username : testjian 
    password : admin  
    driverClassName : oracle.jdbc.driver.OracleDriver
    
  #mvc:  
     #   view:  
           # prefix: /WEB-INF/jsp/  
         #   suffix: .jsp      
  mybatis:
  mapper-locations: classpath*:/mapper/*.xml